run:
  timeout: 5m
  tests: true

linters:
  enable:
    - gofmt
    - goimports
    - govet
    - errcheck
    - staticcheck
    - ineffassign
    - typecheck
    - gosimple
    - gocritic
    - revive
    - misspell

linters-settings:
  gofmt:
    simplify: true
  goimports:
    local-prefixes: github.com/cr0hn/tickhook
  gocritic:
    enabled-tags:
      - performance
      - style
      - experimental
    disabled-checks:
      - commentedOutCode
  revive:
    rules:
      - name: blank-imports
      - name: context-as-argument
      - name: context-keys-type
      - name: error-return
      - name: error-strings
      - name: error-naming
      - name: exported
      - name: increment-decrement
      - name: var-naming
      - name: package-comments

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gosec
        - dupl
    - path: cmd/
      linters:
        - gochecknoglobals